<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150331125915 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE eco_campaign25ji_domain_model_portaluser ADD image VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE eco_campaign25ji_domain_model_portaluser ADD CONSTRAINT FK_234C5ED9C53D045F FOREIGN KEY (image) REFERENCES typo3_media_domain_model_image (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_234C5ED9C53D045F ON eco_campaign25ji_domain_model_portaluser (image)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE eco_campaign25ji_domain_model_portaluser DROP FOREIGN KEY FK_234C5ED9C53D045F");
		$this->addSql("DROP INDEX UNIQ_234C5ED9C53D045F ON eco_campaign25ji_domain_model_portaluser");
		$this->addSql("ALTER TABLE eco_campaign25ji_domain_model_portaluser DROP image");
	}
}