-
  name:  'home'
  uriPattern: ''
  defaults:
    '@controller': 'PortalContent'
    '@action':     'index'

-
  name:  'basic'
  uriPattern: '{@controller}/@action'
  defaults:
    '@controller': 'PortalContent'
    '@action':     'index'