TYPO3:
  Flow:
    security:
      authentication:
        providers:
          TwitterOAuthProvider:
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package':    'Eco.Campaign25ji'
                '@controller': 'Standard'
                '@action':     'welcome'
                '@format':     'html'

Eco:
  Campaign25ji:
    contentList:
      itemsPerPage: 10